#!/usr/bin/env python3
# Generates files that contain Russian (Cyrillic) UI text, written directly as
# UTF-8 bytes. This avoids hand-typing Cyrillic in the editing tool, which is
# error-prone. Run: python3 tools/gen_i18n.py
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "workspace" / "strings.js"

# UI dictionary. Values are plain Russian sentences for the artifacts panel.
STRINGS = {
    "title": "Артефакты",
    "subtitle": "Общее файловое пространство курса. Артефакты, созданные в одной песочнице, доступны в других.",
    "storage": "Хранилище",
    "persist": "Закрепить за браузером",
    "persisted": "Данные закреплены за браузером",
    "notPersisted": "Браузер может очистить данные при нехватке места",
    "used": "Занято",
    "of": "из",
    "empty": "Пока нет артефактов. Запустите код или запрос в песочнице — результат появится здесь.",
    "loadError": "OPFS недоступен в этом браузере.",
    "filterAll": "Все",
    "primary": "основной",
    "files": "файлов",
    "open": "Открыть",
    "copy": "Скопировать путь",
    "copied": "Путь скопирован",
    "download": "Скачать",
    "delete": "Удалить",
    "deleted": "Артефакт удалён",
    "close": "Закрыть",
    "created": "Создан",
    "updated": "Изменён",
    "preview": "Предпросмотр",
    "binaryPreview": "Двоичный файл — предпросмотр недоступен. Используйте скачивание.",
    "type": "Тип",
    "course": "Курс",
    "refresh": "Обновить",
    "count": "артефактов",
    "showSlides": "Слайды",
    "showRaw": "Исходный",
    "copyText": "Скопировать текст",
    "textCopied": "Текст скопирован",
    "closeViewer": "Закрыть просмотр",
    "artifactType": "Тип артефакта",
    "openViewer": "Открыть содержимое",
    "prev": "Назад",
    "next": "Далее",
    "explorerTitle": "Файлы",
    "rootName": "Workspace",
    "newFolder": "Новая папка",
    "newFile": "Новый файл",
    "upload": "Загрузить файлы",
    "rename": "Переименовать",
    "newNamePlaceholder": "Имя",
    "untitledFolder": "Новая папка",
    "untitledFile": "новый.txt",
    "emptyHere": "Папка пуста",
    "deleteConfirm": "Удалить безвозвратно?",
    "deleteFolderConfirm": "Удалить папку со всем содержимым?",
    "confirmDeleteTitle": "Подтвердите удаление",
    "ok": "ОК",
    "collapse": "Свернуть панель",
    "expand": "Показать файлы",
    "openFolder": "Открыть папку",
    "itemsCount": "объектов",
    "uploadFailed": "Не удалось загрузить файл",
}

def main():
    body = "// Russian UI strings for the workspace / artifact bus.\n"
    body += "// Generated by tools/gen_i18n.py — edit there, then re-run.\n"
    body += "export const T = " + json.dumps(STRINGS, ensure_ascii=False, indent=2) + ";\n"
    OUT.write_text(body, encoding="utf-8")
    print("wrote", OUT, "with", len(STRINGS), "keys")

if __name__ == "__main__":
    main()
